name: Future Geeks
description: Your weekly source for all things future tech
markdown: redcarpet
future: true
timezone: America/New_York

# use your ip address when working locally
# BrowserSync uses this for the local server location
# url: your ip address goes here
url: http://futuregeeks.github.io

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: Subscribe
    url: /subscribe/

# http://jekyllrb.com/docs/permalinks/
permalink: /:title/
paginate: 10

sass:
  sass_dir: assets/sass
  style: :compressed
